### ISSUE TITLE
Is there a way to ingest an URL of a PDF (supposedly from a cloud storage), rather than taking the document from directory ?

### ISSUE THREAD

**Issue by 4N1Z** [run-llama/llama_parse#132] opened 2024-04-05 05:17 UTC
Is there a way to ingest an URL of a PDF (supposedly from a cloud storage), rather than taking the document from directory ?

- I have my document uploaded in the Amazon S3, and i want that URL to be parsed. When i went through the documentation, i only got the directoryReader. 
- Checked the source code of llamaParse, didn't find anything useful either !

If there is a way do let me know!.

**Comment by salujav4** [comment] 2024-04-06 17:46
You can send this as a normal fetch request using the following endpoint while converting the pdf into Blob:
https://cloud.llamaindex.ai/api/parsing

**Comment by Disiok** [comment] 2024-08-23 01:22
duplicate of #29

**Closed by Disiok** 2024-08-23 01:22 UTC
Labels: enhancement
