### ISSUE TITLE
LlamaParse not Processing PDFs (2024-09-05)

### ISSUE THREAD

**Issue by adreichert** [run-llama/llama_parse#382] opened 2024-09-05 20:26 UTC
**Describe the bug**
We've noticed that have been no successful LlamaParse jobs since yesterday. Some of our downstream services that utilize LP are also also logging issues.

We sent in some jobs, both with and without third party models, via cURL. When we checked their statuses, also via cURL, we saw the following: `...,"status":"ERROR","error_code":"ERROR_DURING_PROCESSING",...`

To be clear, LlamaParse isn't down in the sense that we don't receive a HTTP response. There seems to be a an issue with the processing.
* We only tested PDFS. 
* We tried both with and without third party multimodal models.

**Job ID**
These are two that failed:
* `29f4c5eb-5074-4e1f-99d5-b3a4996a89a6`
* `07c55bd4-df69-4166-89af-f73a8f1d25af`

**Comment by logan-markewich** [comment] 2024-09-05 20:47
@adreichert im not able to reproduce unfortunately (nor is anyone else on the team)

Are you able to share any files that are resulting in this error?

**Comment by Disiok** [comment] 2024-09-05 21:14
Hey @adreichert, we've identified a small regression on our side. Should be fixed soon!

**Comment by BinaryBrain** [comment] 2024-09-05 21:59
Hi @adreichert,
Sorry for the inconvenience and thanks for reporting the issue.
The problem should be fixed now.

**Comment by adreichert** [comment] 2024-09-05 23:05
@BinaryBrain Parsing has resumed on our end.

**Closed** 2024-09-05 23:06 UTC
Labels: bug
